### PR TITLE
protection for power cycles

### PR DESCRIPTION
**Pull request by alan-stokes**
linked to https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/602

### CODE REVIEW

**Comment by rowleya** [comment]
This probably isn't needed if a value in the cfg file is going to be used instead...

**Comment by alan-stokes** [comment]
no idea where ya got the idea of a value in the cfg being used......... the constant is here coz thats what Luis says is the min.

**Comment by alan-stokes** [comment]
not green?

**Comment by andrewgait** [comment]
> not green?

Not green because of coveralls.  Have to admit I don't know why adding one constant has had that effect...

**Comment by alan-stokes** [comment]
> > not green?
> 
> Not green because of coveralls. Have to admit I don't know why adding one constant has had that effect...

do we really care about coveralls?

**Comment by alan-stokes** [comment]
adds bool returns to facilitate handling when a power off/on doesnt work due to not having bmp data.

**Pull request merged**
