### PR TITLE
Add memory file interface

### PR DESCRIPTION
**Pull request by rowleya**
Adds an interface for reading and writing SDRAM in a file-like way (inspired by rig implementation of the same thing).  Note that this implementation raises exceptions when you go over the region boundaries either in a read, write or seek.  There is also a FileIO implementation that writes to a file instead of SDRAM.  This supports everything that the MemoryIO interface supports, including sub-regions (through slices).
- [x] Completed the initial interfaces
- [x] Add an underlying "file-handle-like" object underneath the MemoryIO that handles the buffering for the object and all sub-objects created from it

### CODE REVIEW

**Comment by alan-stokes** [comment]
Has this bit been done? basically, do you want me to review this now? or at a later date?

￼- [ ] Add an underlying "file-handle-like" object underneath the MemoryIO that handles the buffering for the object and all sub-objects created from it

**Comment by alan-stokes** [comment]
whats the plan with this these days?

**Comment by rowleya** [comment]
Still planning on finishing this eventually

**Comment by alan-stokes** [comment]
ok, just saw a nest of pull requests that eventually land here, was wonering if we could kill / finish them quickly.

**Comment by alan-stokes** [comment]
do we really care about this anymore? as the end users demanding this are gone

**Comment by rowleya** [comment]
This is now ready to go!

**Pull request merged**
