### PR TITLE
Updated to use multiple packets in flight

### PR DESCRIPTION
**Pull request by rowleya**
Enables the "multiple packets in flight" protocol.  This still needs testing.
- [x] Enable Multiple packets in flight and perform preliminary checks.
- [x] Test with large multi-board systems
- [x] Wait for merge of SpiNNakerManchester/spinnaker_tools#25

### CODE REVIEW

**Comment by alan-stokes** [comment]
silly question. with the speed up stuff im doing, does this become obsolete or is it a complimentary thing?

**Comment by rowleya** [comment]
I suspect this is mostly obsoleted by your stuff.  But lets get your stuff in first...

**Comment by dkfellows** [comment]
I was just doing a “bring a branch up to date with `master`”…

**Comment by rowleya** [comment]
This has been tested with the microcircuit and appears to now work well.

**Comment by alan-stokes** [comment]
if it works, you might as well merge it in. ive been doing jiggles around here that shouldnt conflict too badly. who knows, it might add a bit of speed up. as there's some sdp and scp messages in my system. lol. these mainly being the overhead i cant easily remove. router timeout being the main one.

**Pull request merged**
