### PR TITLE
Fix connection selection

### PR DESCRIPTION
**Pull request by rowleya**
Fixes to make connection selection on a big machine actually use most direct connections

### CODE REVIEW

**Comment by dkfellows** [comment]
I'm not sure that this is the right approach; the machine surely knows where the “nearest” ethernets are (they're the board ethernet chips) so you shouldn't have to ask the geometry engine.

**Comment by rowleya** [comment]
Ah yes, this was to not require that you read the machine before using the connections - I can't remember why this was an issue now, but I did it when you were fixing data in and we realised that it might be speaking to the machine over 0, 0 every time, because it didn't have a machine at that point (for some reason).

**Comment by alan-stokes** [comment]
ermm..... so is this still needed?

**Comment by rowleya** [comment]
It could be useful...

**Comment by alan-stokes** [comment]
would need to be de conflicted first. lol. but ok. taking finger off the trash can button

**Comment by Christian-B** [comment]
Is this PR still valid?
In which conflicts need to be resolved.

**Comment by Christian-B** [comment]
is this PR still worth keeping?

**Comment by rowleya** [comment]
In theory it is useful, though in actual fact we use Java quite a bit for this.  The case it is trying to solve is when you haven't read the machine details yet, though you might already know the machine dimensions.  I can't remember the case where this shows up, but it gives a slightly earlier point at which you will be able to use the most direct connection.

**Comment by rowleya** [comment]
Doesn't seem to be a problem...

**Pull request closed without merging**
