### PR TITLE
Check error cores

### PR DESCRIPTION
**Pull request by andrewgait**
I've found that the larger the number of boards I run on, the more likely a job is to fall over inside `transceiver.wait_for_cores_to_be_in_state(...)`; I spent some time trying to get the job to tell me which cores had failed, only to discover that by the time I searched for the error, there were no longer any cores with the error, or possibly that `get_core_state_count(...)` is not returning an accurate value.  This code double-checks whether any cores have reached an error state and if, on the second check, it can't find any, then it allows the job to continue.

I've also included here a script I wrote which I found useful for searching for cores in a particular state across large jobs.

### CODE REVIEW

**Comment by alan-stokes** [comment]
I have 2 mini issues here. 

1. the test,cfg now looks really noisy with loads of commented out ips. which might not be safe. so that needs cleaning.
2. this is coz a core moves from an error state to a none error state. this seems odd in the first place. Cores should never move from such a state to working/finished. So if this is the case, maybe our simulation mapped error states need to be updated? and therefore this check will never truly engage? As the code below this goes off on a number of iterations waiting for cores to reach the expected end states, and should only blow up if it detects a core in a real error state........ or am i misunderstanding this?

**Comment by andrewgait** [comment]
I think the issue here - as far as I understood it, anyway - is that `get_core_state_count(...)` doesn't necessarily return exactly the correct number of processors, as it does depend on a core being able to send a response back in order to be counted, and this count is compared to `all_core_subsets`, which I think was set (much) earlier than this.  The reason I've done this is because, for large jobs (with MCMC), I am currently getting errors at this point, but when I tried to investigate further to find out which cores had failed, it couldn't find any in a failed state.

I'm happy to wait for @rowleya (or maybe @lplana) to comment further on it; to be honest, it probably needs more thought...

**Comment by lplana** [comment]
I don't know how get_core_state_count(...) works, so I can give no authoritative help.

If get_core_state_count(...) uses the 'count' signal supported by spinnaker_tools (sc&mp), then you may need to get the latest 'master' version of spinnaker_tools. There was a bug in the implementation of signal 'count' which manifested in 'large' machines only, resulting in an incorrect (lower) count being returned. This was 'fixed' about a month ago.

My understanding, from conversations with AGR, is that SpiNNMan does *not* use signal 'count'. Instead, it interrogates every core to find its state. In this case, the latest version of spinnaker_tools will *not* help.

**Comment by alan-stokes** [comment]
HI luis. having done a bit of exploring. The get_core_state_count eventually calls this process.
https://github.com/SpiNNakerManchester/SpiNNMan/blob/master/spinnman/transceiver.py#L1323-L1345
which in turns calls this:
https://github.com/SpiNNakerManchester/SpiNNMan/blob/master/spinnman/messages/scp/impl/count_state.py

this looks like a SCP request, and not a per core state request. Its based off app_id and state, thus it cant target a specific core. 

the states its looking for are RTE and WATCHDOG. (found from here: https://github.com/SpiNNakerManchester/SpiNNMan/blob/master/spinnman/transceiver.py#L1999-L2000) 

So if there's a core with such a state, id argue it cant change from that state to a stable state, or if it can, please explain. If it was to return a lower value than the real. aka less than 0. Then i'm confused how our tools would respond to a negative number and all that that intails. if it bounds at 0, then we'd never have seen this error. 

so i think what is basically a delay effect here (the tools rechecking) is a sticky plaster over a issue we've yet to truly diagnose. And given that method does a lot of checking already to wait till the cores are in a stable expected state, id rather not add more onto it to cover up something which seems more dubious and will likely have repercussions elsewhere if not truly diagnosed and fixed. 

@andrewgait  have ya tried with new spinnaker tools? just in case it does rectify the issue?

Is it possible that the count signal is reading a piece of memory that's in flux? aka not locked and the core is actually changing its state at that moment?  and thus your getting a corrupt  item which is being misread as either RTE or WATCHDOG? Im basically spitballing here.

**Comment by rowleya** [comment]
I can confirm that SpiNNMan does use the COUNT signal as a first step, but then in some cases does a check "just in case".  This pull request is for an additional "just in case" that was missed, however as Alan points out, this implies that the COUNT returns > 0 for RTE or WATCHDOG and then we find that no such core is in RTE or WATCHDOG by direct counting.  I may have an explanation for this: the COUNT is based on an app_id, but the core_subsets passed in to this function may be a subset of cores with the given app_id.  Thus if a core not in the subset were to RTE or WATCHDOG, that would result in a positive COUNT but then no such core being found.  In general, this is a bug in the use of this function - it *should* be the case that the core_subset is exactly the set of cores with the app_id, not a subset of them.  This is probably therefore a bug in FEC; this could be protected here though by first checking that the core subset is the set of cores with the given app_id, though this in itself might be quite slow...

**Comment by rowleya** [comment]
See SpiNNakerManchester/SpiNNFrontEndCommon#282

**Comment by alan-stokes** [comment]
hi Andy. does this crash at the ChipRuntimeUpdator? or during another part of the system flow?

**Comment by andrewgait** [comment]
Hi Alan, it usually looks something like this, the crash is in ApplicationRunner during \_run_wait(...):

2018-07-06 02:45:04 ERROR: Error when calling spinn_front_end_common.interface.interface_functions.ApplicationRunner.\__call__ with inputs ['no_sync_changes', 'run_until_complete', 'send_start_notification', 'txrx', 'send_stop_notification', 'notification_interface', 'buffer_manager', 'app_id', 'time_threshold', 'time_scale_factor', 'wait_on_confirmation', 'executable_targets', 'runtime', 'executable_types']
2018-07-06 02:45:04 ERROR: An error has occurred during simulation
2018-07-06 02:45:04 ERROR: 1 cores have reached an error state CPUState.RUN_TIME_EXCEPTION:
Traceback (most recent call last):
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1876, in \_do_run
    executor.execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 626,
 in execute_mapping
    self.\_execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 642,
 in \_execute_mapping
    results = algorithm.call(self.\_internal_type_mapping)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 46, in call
    results = self.call_python(method_inputs)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 58, in call_python
    return method(**inputs)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/application_runner.py", line 62, in \__call__
    time_threshold, run_until_complete)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/application_runner.py", line 111, in run_application
    runtime, time_scale_factor, time_threshold)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/application_runner.py", line 135, in \_run_wait
    self._wait_for_end(txrx, app_id, executable_types)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/application_runner.py", line 149, in \_wait_for_end
    executable_type.end_state, timeout=timeout)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNMan/spinnman/transceiver.py", line 2056, in wait_for_cores_to_be_in_state
    error_cores, cpu_state))
SpinnmanException: 1 cores have reached an error state CPUState.RUN_TIME_EXCEPTION:

**Comment by alan-stokes** [comment]
i was going to propose a accum of the subserts before the wait, till i realised the blasted thing is also absed off executable_type.end_state. yea, rowley's app id vs executable type seems the only sensible approach. Coz i missed this one, so its likely theres others floating around. 

ok, well i guess we have a second solution which will fix the fundermental issue. instead of the sticky plaster. I guess its a decision of whom has time to impl the second solution to see if that fixes it.

you'll find a app_id_tracker within the transceiver somewhere, or something akin to that, which would allow you to allocate a appid per executable type.

**Comment by Christian-B** [comment]
Conflicts need fixing to merge in the latest flake8 fixes

**Comment by andrewgait** [comment]
I think `get_cores_in_run_state.py` should probably be moved somewhere else, if we decide this PR is worth it.  [It's a script I have used to work out which application cores are still running in a large job, rather than having to manually search using ybug/whatever].  I guess we could put it in SupportScripts, though it does depend on `board_test_configuration.py`, which is already a top-level script here...

**Comment by dkfellows** [comment]
Do we want to expose `get_cores_in_run_state.py` as a user-runnable script? (_spalloc_ does this.)

**Comment by andrewgait** [comment]
I don't see why not - the question is, does it go in this repository or somewhere else?

**Comment by rowleya** [comment]
If it only depends on SpiNNMan, this can go there.  If it is really "installed" i.e. like spalloc, this will end up in the PATH, so its location doesn't really matter (and if it isn't installed, instructions can still specify SpiNNMan)

**Comment by dkfellows** [comment]
It only depends on SpiNNMan, and it is now converted and part of the #172 PR, which now supersedes this entirely.

**Pull request closed without merging**
