### PR TITLE
Better sdp handling

### PR DESCRIPTION
**Pull request by rowleya**
Improved handling of SDP and addition of BigData protocol.

Depends on SpiNNakerManchester/spinnaker_tools#110

### CODE REVIEW

**Comment by alan-stokes** [comment]
conflicts

**Comment by dkfellows** [comment]
Is this relevant any more? We now move big data by the Speed Up Data In/Out protocols.

**Comment by rowleya** [comment]
Not needed for 6.0.0 but might want looking at eventually.  Allows for big UDP packets really, but that probably needs extracting and using separately

**Comment by rowleya** [comment]
Probably would need redoing at this point!

**Pull request closed without merging**
