### PR TITLE
Dma caching

### PR DESCRIPTION
**Pull request by alan-stokes**
ads user 2 

tested by https://github.com/SpiNNakerManchester/sPyNNaker/pull/939

### CODE REVIEW

**Review by rowleya — APPROVED** [review]
Looks OK (once green)

**Comment by alan-stokes** [comment]
done

**Comment by dkfellows** [comment]
Is this outdated now?

**Comment by Christian-B** [comment]
This is so old I don't think it is worth saving.

Please reopen if it is.

Will take major effort to bring up to date with master.

**Comment by rowleya** [comment]
The things this does are now done elsewhere anyway

**Pull request closed without merging**
