### PR TITLE
allow better error reporting with ip addresses

### PR DESCRIPTION
**Pull request by alan-stokes**
i think this works. only error tests will tell us such

### CODE REVIEW

**Review by rowleya — APPROVED** [review]
I think this looks OK; you could also add the connection chip_x and chip_y for even more information (that is the chip which has the IP address)

**Comment by alan-stokes** [comment]
> I think this looks OK; you could also add the connection chip_x and chip_y for even more information (that is the chip which has the IP address)

fair. will adjust accordingly.

**Comment by rowleya** [comment]
Yep, still looks good, and better now with the ethernet x and y as well

**Comment by rowleya** [comment]
Is there any way to engineer in a unit test for this given that it doesn't always happen at the integration test level?  I haven't seen the code called yet...

**Comment by alan-stokes** [comment]
ermmmmmmm..................... unless we can make a test that specifially targets a dodgy board. i cant think how. par from maybe rince and repeat till it goes boom

**Comment by dkfellows** [comment]
Waiting until we get the right kind of failure so we can test this! 😁

**Review by dkfellows — APPROVED** [review]
This appears to do the right thing in integration testing.

**Pull request merged**
